version: "1.0"

services:
  app:
    build: . # build from Dockerfile
    command: python3 main.py
    env_file:
      - .env
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    x-develop: # Enable compose watch
      watch:
        - path: ./src/
          action: rebuild